export const metaData = [
    {
        // ['blue', 'green', 'yellow', 'orange', 'red', 'purple',
        // 'grey', 'proudPink', 'paleBlue', 'paleOrange', 'palePurple']
        backgroundColor: '',
        
        // ['blue', 'green', 'yellow', 'orange', 'red', 'purple',
        // 'grey', 'proudWhite', 'paleBlue', 'paleOrange', 'palePurple']
        frameColor: '',

                // ['blue', 'green', 'yellow', 'orange', 'red', 'purple',
        // 'grey', 'proudPink', 'paleBlue', 'paleOrange', 'palePurple']
        skinColor: '',

                // ['blue', 'green', 'yellow', 'orange', 'red', 'purple',
        // 'grey', 'proudPink', 'paleBlue', 'paleOrange', 'palePurple']
        hairColor: '',

        // ['codeHead', 'cartoonHead', 'radioHead', 'slivioHead', 'abbyHead',
        // 'coconutHead', 'mohawkHead', 'creamHead', 'masculineSkull', 'feminineSkull',
        // 'pentagonalHead', 'abrahamHead', 'maskulineHead', 'femaskHead', 'femmeFatale',
        // 'umbrellaHead', 'puffHead', 'ponyHead', 'logoHead', 'scheherazadeHead',
        // 'catHatter1', 'catHatter2', 'catHatter3']
        head:'',

        //['10/10', '20/20', '10/20', '0/20', '30/30',
        //'']
        eyesight: '',

        // ['open', 'close']
        mouth: '',

        //['earing', 'mask', 'crown', 'piercing', 'glasses',
        // 'none']
        accessory1: '',

        //['earing', 'mask', 'crown', 'piercing', 'glasses',
        // 'none']
        accessory2: ''
    },
    {
        assetName: 'ah001',
        backgroundColor: 'orange',
        frameColor: 'grey',
        skinColor: 'green',
        hairColor: 'green',
        head:'abby',
        eyesight: '20/20',
        mouth: 'closed',
        accessory1: 'earing/piercing',
        accessory2: 'crown',
        accessory3: 'none'
    },
    {
        assetName: 'ah002',
        backgroundColor: 'blue',
        frameColor: 'yellow',
        skinColor: 'yellow',
        hairColor: 'yellow',
        head:'codeHead',
        eyesight: '20/20',
        mouth: 'open',
        accessory1: 'earing/piercing',
        accessory2: 'none',
        accessory3: 'none'
    },
    {
        assetName: 'ah003',
        backgroundColor: 'red',
        frameColor: 'green',
        skinColor: 'blue',
        hairColor: 'blue',
        head:'scheherazade',
        eyesight: '20/20',
        mouth: 'closed',
        accessory1: 'none',
        accessory2: 'none',
        accessory3: 'none'
    },
    {
        assetName: 'ah004',
        backgroundColor: 'purple',
        frameColor: 'orange',
        skinColor: 'orange',
        hairColor: 'orange',
        head:'coconut',
        eyesight: '20/20',
        mouth: 'closed',
        accessory1: 'none',
        accessory2: 'none',
        accessory3: 'none'
    },
    {
        assetName: 'ah005',
        backgroundColor: 'blue',
        frameColor: 'orange',
        skinColor: 'blue',
        hairColor: 'sunKiss',
        head:'feminineSkull',
        eyesight: '20/20',
        mouth: 'open',
        accessory1: 'earing/piercing',
        accessory2: 'none',
        accessory3: ''
    },
    {
        assetName: 'ah006',
        backgroundColor: 'green',
        frameColor: 'purple',
        skinColor: 'red',
        hairColor: 'red',
        head:'cartoonHead',
        eyesight: '20/20',
        mouth: 'closed',
        accessory1: 'mustache',
        accessory2: 'none',
        accessory3: 'none'
    },
    {
        assetName: 'ah007',
        backgroundColor: 'green',
        frameColor: 'blue',
        skinColor: 'grey',
        hairColor: 'grey',
        head:'radioHead',
        eyesight: '20/20',
        mouth: 'closed',
        accessory1: 'earing/piercing',
        accessory2: 'none',
        accessory3: 'none'
    },
    {
        assetName: 'ah008',
        backgroundColor: 'purple',
        frameColor: 'grey',
        skinColor: 'green',
        hairColor: 'green',
        head:'silvio',
        eyesight: '20/20',
        mouth: 'closed',
        accessory1: 'none',
        accessory2: 'none',
        accessory3: 'none'
    },
    {
        assetName: 'ah009',
        backgroundColor: 'blue',
        frameColor: 'green',
        skinColor: 'red',
        hairColor: 'red',
        head:'puffy',
        eyesight: '30/30',
        mouth: 'closed',
        accessory1: 'earing/piercing',
        accessory2: 'crown',
        accessory3: 'none'
    },
    {
        assetName: 'ah010',
        backgroundColor: 'red',
        frameColor: 'grey',
        skinColor: 'yellow',
        hairColor: 'transparent',
        head:'masculineSkull',
        eyesight: '17/20',
        mouth: 'closed',
        accessory1: 'glasses',
        accessory2: 'wire',
        accessory3: 'none'
    },
    {
        assetName: 'ah011',
        backgroundColor: 'green',
        frameColor: 'purple',
        skinColor: 'orange',
        hairColor: 'orange',
        head:'scheherazade',
        eyesight: '20/20',
        mouth: 'closed',
        accessory1: 'earing/piercing',
        accessory2: 'mask',
        accessory3: 'vampTeeth'
    },
    {
        assetName: 'ah012',
        backgroundColor: 'yellow',
        frameColor: 'red',
        skinColor: 'blue',
        hairColor: 'blue',
        head:'mohawk',
        eyesight: '10/10',
        mouth: 'open',
        accessory1: 'none',
        accessory2: 'none',
        accessory3: 'none'
    },
    {
        assetName: 'ah013',
        backgroundColor: 'yellow',
        frameColor: 'grey',
        skinColor: 'red',
        hairColor: 'red',
        head:'abby',
        eyesight: '20/20',
        mouth: 'open',
        accessory1: 'none',
        accessory2: 'none',
        accessory3: 'none'
    },
    {
        assetName: 'ah014',
        backgroundColor: 'grey',
        frameColor: 'red',
        skinColor: 'purple',
        hairColor: 'purple',
        head:'coconut',
        eyesight: '20/20',
        mouth: 'closed',
        accessory1: 'earing/piercing',
        accessory2: 'mask',
        accessory3: 'none'
    },
    {
        assetName: 'ah015',
        backgroundColor: 'yellow',
        frameColor: 'orange',
        skinColor: 'orange',
        hairColor: 'blue',
        head:'catHatter',
        eyesight: '40/40',
        mouth: 'closed',
        accessory1: 'none',
        accessory2: 'crown',
        accessory3: 'none'
    },
    {
        assetName: 'ah016',
        backgroundColor: '',
        frameColor: '',
        skinColor: '',
        hairColor: '',
        head:'pentagonal',
        eyesight: '11/20',
        mouth: 'closed',
        accessory1: 'earing/piercing',
        accessory2: 'crown',
        accessory3: 'none'
    },
    {
        assetName: 'ah017',
        backgroundColor: '',
        frameColor: '',
        skinColor: '',
        hairColor: '',
        head:'pony',
        eyesight: '0/20',
        mouth: 'open',
        accessory1: 'none',
        accessory2: 'none',
        accessory3: 'none'
    },
    {
        assetName: 'ah018',
        backgroundColor: '',
        frameColor: '',
        skinColor: '',
        hairColor: '',
        head:'abraham',
        eyesight: '10/20',
        mouth: 'closed',
        accessory1: 'earing/piercing',
        accessory2: 'none',
        accessory3: 'none'
    },
    {
        assetName: 'ah019',
        backgroundColor: '',
        frameColor: '',
        skinColor: '',
        hairColor: '',
        head:'umbrella',
        eyesight: '80/80',
        mouth: 'closed',
        accessory1: 'none',
        accessory2: 'none',
        accessory3: 'none'
    },
    {
        assetName: 'ah020',
        backgroundColor: '',
        frameColor: '',
        skinColor: '',
        hairColor: '',
        head:'abraham',
        eyesight: '20/20',
        mouth: 'open',
        accessory1: 'none',
        accessory2: 'bonePiercing',
        accessory3: 'none'
    },
    {
        assetName: 'ah021',
        backgroundColor: '',
        frameColor: '',
        skinColor: '',
        hairColor: '',
        head:'radioHead',
        eyesight: '20/20',
        mouth: 'open',
        accessory1: 'earing/piercing',
        accessory2: 'wire',
        accessory3: 'none'
    },
    {
        assetName: 'ah022',
        backgroundColor: '',
        frameColor: '',
        skinColor: '',
        hairColor: '',
        head:'cartoonHead',
        eyesight: '11/20',
        mouth: 'closed',
        accessory1: 'none',
        accessory2: 'none',
        accessory3: 'none'
    },
    {
        assetName: 'ah023',
        backgroundColor: '',
        frameColor: '',
        skinColor: '',
        hairColor: '',
        head:'logoHead',
        eyesight: '20/20',
        mouth: 'closed',
        accessory1: 'none',
        accessory2: 'none',
        accessory3: 'none'
    },
    {
        assetName: 'ah024',
        backgroundColor: '',
        frameColor: '',
        skinColor: '',
        hairColor: '',
        head:'creamy',
        eyesight: '20/20',
        mouth: 'closed',
        accessory1: 'mustache',
        accessory2: 'none',
        accessory3: 'none'
    },
    {
        assetName: 'ah025',
        backgroundColor: '',
        frameColor: '',
        skinColor: '',
        hairColor: '',
        head:'feminineSkull',
        eyesight: '10/10',
        mouth: 'open',
        accessory1: 'earing/piercing',
        accessory2: 'none',
        accessory3: 'none'
    },
    {
        assetName: 'ah026',
        backgroundColor: '',
        frameColor: '',
        skinColor: '',
        hairColor: '',
        head:'codeHead',
        eyesight: '20/20',
        mouth: 'closed',
        accessory1: 'mustache',
        accessory2: 'none',
        accessory3: 'none'
    },
    {
        assetName: 'ah027',
        backgroundColor: '',
        frameColor: '',
        skinColor: '',
        hairColor: '',
        head:'pony',
        eyesight: '20/20',
        mouth: 'closed',
        accessory1: 'earing/piercing',
        accessory2: 'bubbleGum',
        accessory3: 'none'
    },
    {
        assetName: 'ah028',
        backgroundColor: '',
        frameColor: '',
        skinColor: '',
        hairColor: '',
        head:'abraham',
        eyesight: '20/20',
        mouth: 'closed',
        accessory1: 'bandAid',
        accessory2: 'none',
        accessory3: 'none'
    },
    {
        assetName: 'ah029',
        backgroundColor: '',
        frameColor: '',
        skinColor: '',
        hairColor: '',
        head:'logoHead',
        eyesight: '20/20',
        mouth: 'open',
        accessory1: 'earing/piercing',
        accessory2: 'none',
        accessory3: 'none'
    },
    {
        assetName: 'ah030',
        backgroundColor: '',
        frameColor: '',
        skinColor: '',
        hairColor: '',
        head:'maskuline',
        eyesight: '20/20',
        mouth: 'open',
        accessory1: 'earing/piercing',
        accessory2: 'mask',
        accessory3: 'vampTeeth'
    },
    {
        assetName: 'ah031',
        backgroundColor: '',
        frameColor: '',
        skinColor: '',
        hairColor: '',
        head:'radioHead',
        eyesight: '20/20',
        mouth: 'closed',
        accessory1: 'earing/piercing',
        accessory2: 'none',
        accessory3: 'none'
    },
    {
        assetName: 'ah031',
        backgroundColor: '',
        frameColor: '',
        skinColor: '',
        hairColor: '',
        head:'creamy',
        eyesight: '20/20',
        mouth: 'closed',
        accessory1: 'none',
        accessory2: 'none',
        accessory3: 'none'
    },
    {
        assetName: 'ah033',
        backgroundColor: '',
        frameColor: '',
        skinColor: '',
        hairColor: '',
        head:'umbrella',
        eyesight: '20/20',
        mouth: 'closed',
        accessory1: 'none',
        accessory2: 'none',
        accessory3: 'none'
    },
    {
        assetName: 'ah034',
        backgroundColor: '',
        frameColor: '',
        skinColor: '',
        hairColor: '',
        head:'abraham',
        eyesight: '20/20',
        mouth: 'closed',
        accessory1: 'mustache',
        accessory2: 'none',
        accessory3: 'none'
    },
    {
        assetName: 'ah035',
        backgroundColor: '',
        frameColor: '',
        skinColor: '',
        hairColor: '',
        head:'feminineSkull',
        eyesight: '10/20',
        mouth: 'open',
        accessory1: 'earing/piercing',
        accessory2: 'bonePiercing',
        accessory3: 'none'
    },
    {
        assetName: 'ah036',
        backgroundColor: '',
        frameColor: '',
        skinColor: '',
        hairColor: '',
        head:'codeHead',
        eyesight: '20/20',
        mouth: 'closed',
        accessory1: 'none',
        accessory2: 'none',
        accessory3: 'none'
    },
    {
        assetName: 'ah037',
        backgroundColor: '',
        frameColor: '',
        skinColor: '',
        hairColor: '',
        head:'abby',
        eyesight: '10/20',
        mouth: 'closed',
        accessory1: 'none',
        accessory2: 'none',
        accessory3: 'none'
    },
    {
        assetName: 'ah038',
        backgroundColor: '',
        frameColor: '',
        skinColor: '',
        hairColor: '',
        head:'silvio',
        eyesight: '30/30',
        mouth: 'closed',
        accessory1: 'mustache',
        accessory2: 'none',
        accessory3: 'none'
    },
    {
        assetName: 'ah039',
        backgroundColor: '',
        frameColor: '',
        skinColor: '',
        hairColor: '',
        head:'scheherazade',
        eyesight: '11/20',
        mouth: 'closed',
        accessory1: 'earing/piercing',
        accessory2: 'none',
        accessory3: 'none'
    },
    {
        assetName: 'ah040',
        backgroundColor: '',
        frameColor: '',
        skinColor: '',
        hairColor: '',
        head:'masculineSkull',
        eyesight: '15/20',
        mouth: 'open',
        accessory1: 'none',
        accessory2: 'bonePiercing',
        accessory3: 'none'
    },
]